version: '3.8'
services:
  front:
    container_name: front
    build:
      target: dev
      context: .
      dockerfile: .docker/front/Dockerfile
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"